# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8276ae0f56a41433e88868fe6545feaca128ce1f1931c4beba2a63b99edf2ee947abbb1e8a0f015fca6ff3fa7d7f09c4049dbb1d4ddd2c66e27e35b3747f88a5

test:
  secret_key_base: c278d8234fdc08e80a52d199ef3595618cb9fdbdfa06000960a5672abc7c819381ab557774c4328637aeecf5d79e7aca1fabb2d44dad43b54e67737b8a585d94

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
